#!/bin/bash
# briefing-demo.sh [--screenshots] [DIR] — build the README's `my-api` demo
# project and render its session briefing. --screenshots also rewrites
# docs/briefing-{index,session,health}.png with headless Chrome.
#
# DIR defaults to $TMPDIR/vibe-learn-demo/my-api. A prior generated demo can
# be recreated; an existing directory without the demo marker is left alone.
# The session continues the JWT auth example used throughout the README; the
# health history is tests/fixtures/health-sample.sh (the mockup's data). HOME
# points inside DIR so nothing is read from or written to your real
# ~/.vibe-learn.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCREENSHOTS=false
if [ "${1:-}" = "--screenshots" ]; then SCREENSHOTS=true; shift; fi
PROJECT="${1:-${TMPDIR:-/tmp}/vibe-learn-demo/my-api}"
PROJECT="${PROJECT%/}"
case "$(basename "$PROJECT")" in my-api) ;; *) echo "DIR must end in /my-api" >&2; exit 1 ;; esac

if [ -e "$PROJECT" ] || [ -L "$PROJECT" ]; then
  if [ -L "$PROJECT" ] || [ ! -f "$PROJECT/.vibe-learn-demo" ]; then
    echo "Refusing to replace an existing non-demo directory: $PROJECT" >&2
    exit 1
  fi
  rm -rf "$PROJECT"
fi
mkdir -p "$PROJECT/src/routes" "$PROJECT/src/middleware" "$PROJECT/.vibe-learn" "$PROJECT/.home"
printf 'Generated by docs/demo/briefing-demo.sh\n' > "$PROJECT/.vibe-learn-demo"
export HOME="$PROJECT/.home"
cd "$PROJECT"

git init -q
git config user.email demo@example.com
git config user.name demo
cat > src/routes/user.ts <<'EOF'
import { Router } from "express";

const router = Router();

router.get("/profile", (req, res) => res.json({ id: 1 }));
router.get("/settings", (req, res) => res.json({ theme: "dark" }));

export default router;
EOF
echo '{"name":"my-api","dependencies":{"express":"^4.19.2"}}' > package.json
git add -A && git commit -qm "initial routes"

cat > src/middleware/auth.ts <<'EOF'
import type { Request, Response, NextFunction } from "express";
import jwt from "jsonwebtoken";

const secret = process.env.JWT_SECRET ?? "";

// Fail closed: every path that doesn't verify a token returns 401.
export function requireAuth(req: Request, res: Response, next: NextFunction) {
  const header = req.headers.authorization ?? "";
  const token = header.startsWith("Bearer ") ? header.slice(7) : "";
  if (!token || !secret) return res.status(401).json({ error: "unauthorized" });

  try {
    const payload = jwt.verify(token, secret);
    (req as Request & { user?: unknown }).user = payload;
    return next();
  } catch {
    return res.status(401).json({ error: "invalid token" });
  }
}
EOF
cat > src/routes/user.ts <<'EOF'
import { Router } from "express";
import { requireAuth } from "../middleware/auth";

const router = Router();
router.use(requireAuth);

router.get("/profile", (req, res) => res.json({ id: 1 }));
router.get("/settings", (req, res) => res.json({ theme: "dark" }));

export default router;
EOF
echo '{"name":"my-api","dependencies":{"express":"^4.19.2","jsonwebtoken":"^9.0.2"}}' > package.json

D="$(date -u +%Y-%m-%d)"
ts() { printf '%sT%s:00Z' "$D" "$1"; }
ev() { jq -cn "$@"; }
{
  ev --arg t "$(ts 14:02)" '{timestamp:$t,event:"user_prompt",turn:1,prompt:"add JWT auth middleware so /profile and /settings need a valid token"}'
  ev --arg t "$(ts 14:03)" '{timestamp:$t,event:"tool_use",turn:1,tool:"Bash",command:"npm install jsonwebtoken",action:"ran",context:{exit_code:0}}'
  ev --arg t "$(ts 14:04)" '{timestamp:$t,event:"tool_use",turn:1,tool:"Write",file:"src/middleware/auth.ts",action:"created",context:{new_file:true}}'
  ev --arg t "$(ts 14:05)" '{timestamp:$t,event:"tool_use",turn:1,tool:"Edit",file:"src/routes/user.ts",action:"edited",context:{}}'
  ev --arg t "$(ts 14:06)" '{timestamp:$t,event:"tool_use",turn:1,tool:"Bash",command:"npm test",action:"ran",context:{exit_code:1}}'
  ev --arg t "$(ts 14:07)" '{timestamp:$t,event:"tool_use",turn:1,tool:"Edit",file:"src/middleware/auth.ts",action:"edited",context:{}}'
  ev --arg t "$(ts 14:08)" '{timestamp:$t,event:"tool_use",turn:1,tool:"Bash",command:"npm test",action:"ran",context:{exit_code:1}}'
  ev --arg t "$(ts 14:09)" '{timestamp:$t,event:"turn_end",turn:1,model:"claude-opus-5.5",effort:"high"}'
  ev --arg t "$(ts 14:11)" '{timestamp:$t,event:"user_prompt",turn:2,prompt:"the expired-token test still fails"}'
  ev --arg t "$(ts 14:12)" '{timestamp:$t,event:"tool_use",turn:2,tool:"Edit",file:"src/middleware/auth.ts",action:"edited",context:{}}'
  ev --arg t "$(ts 14:13)" '{timestamp:$t,event:"tool_use",turn:2,tool:"Write",file:"test/auth.test.ts",action:"created",context:{new_file:true}}'
  ev --arg t "$(ts 14:14)" '{timestamp:$t,event:"tool_use",turn:2,tool:"Bash",command:"npm test",action:"ran",context:{exit_code:1}}'
  ev --arg t "$(ts 14:15)" '{timestamp:$t,event:"tool_use",turn:2,tool:"Edit",file:"test/auth.test.ts",action:"edited",context:{}}'
  ev --arg t "$(ts 14:16)" '{timestamp:$t,event:"tool_use",turn:2,tool:"Bash",command:"npm test",action:"ran",context:{exit_code:0}}'
  ev --arg t "$(ts 14:17)" '{timestamp:$t,event:"turn_end",turn:2,model:"claude-opus-5.5",effort:"high"}'
  ev --arg t "$(ts 14:20)" '{timestamp:$t,event:"user_prompt",turn:3,prompt:"/learn why does the auth check run before the route handlers?"}'
  ev --arg t "$(ts 14:22)" '{timestamp:$t,event:"user_prompt",turn:4,prompt:"move the secret check to startup so a missing JWT_SECRET fails fast"}'
  ev --arg t "$(ts 14:23)" '{timestamp:$t,event:"tool_use",turn:4,tool:"Edit",file:"src/middleware/auth.ts",action:"edited",context:{}}'
  ev --arg t "$(ts 14:24)" '{timestamp:$t,event:"tool_use",turn:4,tool:"Bash",command:"npx tsc --noEmit",action:"ran",context:{exit_code:0}}'
  ev --arg t "$(ts 14:25)" '{timestamp:$t,event:"tool_use",turn:4,tool:"Bash",command:"npm test",action:"ran",context:{exit_code:0}}'
  ev --arg t "$(ts 14:26)" '{timestamp:$t,event:"turn_end",turn:4,model:"claude-opus-5.5",effort:"high"}'
} > .vibe-learn/session-log.jsonl

# A Claude Code transcript with only the tool calls usage.sh counts.
tool() {
  local input="${2:-}"
  jq -cn --arg t "$(ts 14:10)" --arg n "$1" --argjson i "${input:-null}" \
    '{type:"assistant",timestamp:$t,message:{content:[{type:"tool_use",name:$n,input:($i // {})}]}}'
}
{
  for _ in 1 2 3 4 5 6 7 8 9; do tool Read; done
  for _ in 1 2 3 4 5 6 7; do tool Grep; done
  for _ in 1 2 3 4 5 6 7; do tool Bash; done
  for _ in 1 2 3 4 5 6; do tool Edit; done
  tool Write; tool Write
  tool Skill '{"skill":"explain"}'
} > .home/transcript.jsonl

jq -n --arg t "$(ts 14:02)" --arg tp "$HOME/transcript.jsonl" '{
  session_id: "demo-jwt-auth", started_at: $t, event_count: 17, current_turn: 4,
  harness: "claude-code", harness_version: "2.5.0", model: "claude-opus-5.5", effort: "high",
  transcript_path: $tp, git_head: null, git_dirty: true}' > .vibe-learn/session-meta.json

cat > .vibe-learn/pause-summary.txt <<'EOF'
⏸ vibe-learn — what just happened:
Goal: move the secret check to startup so a missing JWT_SECRET fails fast

  ✦ Created src/middleware/auth.ts
  ✦ Created test/auth.test.ts
  ✦ Edited src/routes/user.ts
  ✦ Ran: npm install jsonwebtoken
  ✦ Ran: npm test (passed after 3 failures)

 /learn [question]  ·  /digest  ·  /quiz  ·  vibe-learn briefing  ·  vibe-learn audio-prep
EOF

jq -n --arg d "$D" '{version: 1, concepts: [
  {name: "express-middleware-ordering", label: "Express middleware ordering", first_seen: $d, last_seen: $d,
   sessions: 2, last_quizzed: $d, status: "shaky", notes: "had the what, not the when"},
  {name: "jwt-verification", label: "JWT verification", first_seen: $d, last_seen: $d,
   sessions: 2, last_quizzed: $d, status: "solid", notes: ""},
  {name: "fail-closed-auth", label: "Fail-closed auth", first_seen: $d, last_seen: $d,
   sessions: 1, last_quizzed: $d, status: "solid", notes: ""}]}' > .vibe-learn/knowledge.json

bash "$REPO/tests/fixtures/health-sample.sh" 1 > .vibe-learn/health.jsonl

bash "$REPO/scripts/briefing.sh" "$PROJECT" >/dev/null
BRIEFING="$PROJECT/.vibe-learn/briefing"
echo "$BRIEFING"
$SCREENSHOTS || exit 0

CHROME="${CHROME:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}"
[ -x "$CHROME" ] || CHROME="$(command -v google-chrome || command -v chromium || true)"
[ -x "$CHROME" ] || { echo "Chrome not found; set CHROME=/path/to/chrome" >&2; exit 1; }

# shot PAGE OUT HEIGHT — 1280 CSS px wide at 2x. Headless Chrome can linger
# after writing the file, so wait for the file and then stop it.
shot() {
  local out="$REPO/docs/$2" profile pid tmp_dir tmp_out
  profile="$(mktemp -d)"
  tmp_dir="$(mktemp -d)"
  tmp_out="$tmp_dir/$2"
  "$CHROME" --headless=new --disable-gpu --hide-scrollbars --force-device-scale-factor=2 \
    --window-size="1280,$3" --user-data-dir="$profile" --screenshot="$tmp_out" \
    "file://$BRIEFING/$1" >/dev/null 2>&1 &
  pid=$!
  for _ in $(seq 1 60); do
    [ -s "$tmp_out" ] && break
    kill -0 "$pid" 2>/dev/null || break
    sleep 0.5
  done
  [ -s "$tmp_out" ] && sleep 0.5
  kill "$pid" 2>/dev/null || true
  wait "$pid" 2>/dev/null || true
  rm -rf "$profile"
  if [ ! -s "$tmp_out" ]; then
    rm -rf "$tmp_dir"
    echo "Screenshot failed for $1; kept $out" >&2
    return 1
  fi
  mv "$tmp_out" "$out"
  rm -rf "$tmp_dir"
  echo "$out"
}
session="$(cd "$BRIEFING" && ls sessions/*.html | head -1)"
shot index.html briefing-index.png 720
shot "$session" briefing-session.png 960
shot health.html briefing-health.png 1380
